// Create post
// 401 if Unauthorized

POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: $argon2id$v=19$m=65536,t=2,p=1$liouN0uS6MchCLgHGi4NkFXGp/2eHZbEA5lPBQDtNPo$nAhf9SqZGbk3OpOxKAb1kuviOBrylsOOuDUBA5lCf1w

{
    "title": "another test message",
    "content": "Welcome to my app!~"
}