// Get one post
// 401 if unauthorized

// Replace 1 with post id (1 is valid though)
GET http://localhost:3000/api/posts/1
Content-Type: application/json
Authorization: $argon2id$v=19$m=65536,t=2,p=1$zUBBJnRv1du0w5vr2WMzin2ZEY5GtIT+1OW4ICU9RLY$lyH82UxzB9uIrfV81hvr3k6pnhnRzEg9I06CrO3zLEc