// Get newest posts
// 401 if Unauthorized

GET http://localhost:3000/api/posts/newest
Content-Type: application/json
Authorization: $argon2id$v=19$m=65536,t=2,p=1$NtYxdZbdJVMRnHeSmPtFAz24GztKHgMiViiTvSKbLLc$zqmP49Jm3iquvsd4CALfqiRAoHwDNv2tdl3btdNDUFM